services:
  proxy:
    ports: !override
      - "8080:8080"
    develop:
      watch:
        - path: ./services/proxy
          target: /etc/caddy
          ignore:
            - "*"
            - "!Caddyfile"
          action: sync+restart

  db:
    volumes:
      - ./services/db/migrations:/wfd/db/migrations
      - ./services/db/startup.sh:/docker-entrypoint-initdb.d/startup.sh

  marketing-site:
    image: !reset "null"
    build: !override
      target: marketing-site-dev
    volumes:
      - ./services/marketing-site:/app/services/marketing-site

  webapp:
    image: !reset "null"
    build:
      target: base
    working_dir: /app/services/web
    command: bun run dev --host
    volumes:
      - .:/app

  api:
    image: !reset "null"
    build:
      target: base
    working_dir: /app/services/api
    command: bun --watch .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/app

  supertokens:
    ports:
      - ${SUPERTOKENS_PORT}:${SUPERTOKENS_PORT}

  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  stripe:
    container_name: stripe
    image: stripe/stripe-cli:latest
    entrypoint: stripe listen --api-key "$STRIPE_KEY" --forward-to "http://api:${API_PORT}/api/stripe/webhook"
    environment:
      - API_PORT
      - STRIPE_KEY
