name: Build & Deploy Web

on:
  push:
    branches: ["main"]
    paths:
      - web/**
      - packages/**
      - shared/**
      - .github/build-deploy-web.yml
      - pnpm-lock.yaml

env:
  PROJECT_ID: workflow-dog  # Google Cloud project id
  GAR_LOCATION: us-central1 # Artifact Registry location
  SERVICE: web # Cloud Run service name
  REGION: us-central1 # Cloud Run service region
  REPO: workflow-dog

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup variables
        run: echo "IMAGE_TAG=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}" > $GITHUB_ENV

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GH_ACTIONS_SERVICE_ACCOUNT_KEY }}

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Create service-account.json
        run: echo '${{ secrets.API_SERVER_SERVICE_ACCOUNT_KEY }}' > web/service-account.json

      - name: Create .env
        run: echo '${{ secrets.WEB_ENV }}' > web/.env

      - name: Build container
        run: docker build -t "$IMAGE_TAG" -f ./web/Dockerfile .

      - name: Push Container
        run: docker push "$IMAGE_TAG"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_TAG }}